"""enrich session device context

Revision ID: da347f581faa
Revises: d60ff7fee46b
Create Date: 2026-05-11 04:41:33.903808

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "da347f581faa"
down_revision: str | None = "d60ff7fee46b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("session", sa.Column("last_active_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("session", sa.Column("asn_org", sa.String(length=128), nullable=True))
    op.add_column("session", sa.Column("ip_type", sa.String(length=32), nullable=True))
    op.add_column("session", sa.Column("device_type", sa.String(length=32), nullable=True))
    op.add_column("session", sa.Column("os_name", sa.String(length=64), nullable=True))
    op.add_column("session", sa.Column("browser_name", sa.String(length=64), nullable=True))
    op.add_column("session", sa.Column("timezone", sa.String(length=64), nullable=True))
    op.add_column("session", sa.Column("screen_width", sa.SmallInteger(), nullable=True))
    op.add_column("session", sa.Column("pixel_ratio", sa.Float(), nullable=True))
    op.add_column("session", sa.Column("webgl_vendor", sa.String(length=128), nullable=True))
    op.add_column("session", sa.Column("webgl_renderer", sa.String(length=256), nullable=True))
    op.add_column("session", sa.Column("hardware_concurrency", sa.SmallInteger(), nullable=True))
    op.add_column("session", sa.Column("device_memory", sa.Float(), nullable=True))
    op.add_column("session", sa.Column("languages", sa.ARRAY(sa.String()), nullable=True))
    op.drop_column("session", "fingerprint")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "session",
        sa.Column("fingerprint", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    )
    op.drop_column("session", "languages")
    op.drop_column("session", "device_memory")
    op.drop_column("session", "hardware_concurrency")
    op.drop_column("session", "webgl_renderer")
    op.drop_column("session", "webgl_vendor")
    op.drop_column("session", "pixel_ratio")
    op.drop_column("session", "screen_width")
    op.drop_column("session", "timezone")
    op.drop_column("session", "browser_name")
    op.drop_column("session", "os_name")
    op.drop_column("session", "device_type")
    op.drop_column("session", "ip_type")
    op.drop_column("session", "asn_org")
    op.drop_column("session", "last_active_at")
    # ### end Alembic commands ###
