"""add app_id to tenant

Revision ID: 35978c704c77
Revises: da347f581faa
Create Date: 2026-05-12 14:35:16.830694

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "35978c704c77"
down_revision: str | None = "da347f581faa"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tenant", sa.Column("app_id", sa.String(length=64), nullable=True))
    op.create_index(op.f("ix_tenant_tenant_app_id"), "tenant", ["app_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tenant_tenant_app_id"), table_name="tenant")
    op.drop_column("tenant", "app_id")
    # ### end Alembic commands ###
