"""add profile table

Revision ID: d60ff7fee46b
Revises: 00485e6155c8
Create Date: 2026-05-10 21:09:28.588070

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d60ff7fee46b"
down_revision: str | None = "00485e6155c8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "profile",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=True),
        sa.Column("avatar_url", sa.String(length=512), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk_profile_user_id_user"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_profile")),
    )
    op.create_index(op.f("ix_profile_profile_user_id"), "profile", ["user_id"], unique=True)
    op.create_foreign_key(
        op.f("fk_tenant_owner_id_user"), "tenant", "user", ["owner_id"], ["id"], use_alter=True
    )
    op.drop_column("user", "first_name")
    op.drop_column("user", "avatar_url")
    op.drop_column("user", "last_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("last_name", sa.VARCHAR(length=100), autoincrement=False, nullable=False)
    )
    op.add_column(
        "user", sa.Column("avatar_url", sa.VARCHAR(length=512), autoincrement=False, nullable=True)
    )
    op.add_column(
        "user", sa.Column("first_name", sa.VARCHAR(length=100), autoincrement=False, nullable=False)
    )
    op.drop_constraint(op.f("fk_tenant_owner_id_user"), "tenant", type_="foreignkey")
    op.drop_index(op.f("ix_profile_profile_user_id"), table_name="profile")
    op.drop_table("profile")
    # ### end Alembic commands ###
