"""initial schema

Revision ID: 00485e6155c8
Revises:
Create Date: 2026-04-30 02:59:20.911879

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "00485e6155c8"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "permission",
        sa.Column("codename", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_permission")),
    )
    op.create_index(
        op.f("ix_permission_permission_codename"), "permission", ["codename"], unique=True
    )
    op.create_table(
        "queue_job",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("queue_name", sa.String(length=128), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("execution_lock", sa.String(length=128), nullable=True),
        sa.Column("queueing_lock", sa.String(length=128), nullable=True),
        sa.Column("args", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("abort_requested", sa.Boolean(), nullable=False),
        sa.Column("worker_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_queue_job")),
    )
    op.create_index(
        op.f("ix_queue_job_queue_job_execution_lock"),
        "queue_job",
        ["execution_lock"],
        unique=True,
        postgresql_where=sa.text("status = 'doing'"),
    )
    op.create_index(
        op.f("ix_queue_job_queue_job_priority_queue_job_id"),
        "queue_job",
        ["priority", "id"],
        unique=False,
        postgresql_where=sa.text("status = 'todo'"),
    )
    op.create_index(
        op.f("ix_queue_job_queue_job_queue_name"), "queue_job", ["queue_name"], unique=False
    )
    op.create_index(
        op.f("ix_queue_job_queue_job_queueing_lock"),
        "queue_job",
        ["queueing_lock"],
        unique=True,
        postgresql_where=sa.text("status = 'todo'"),
    )
    op.create_index(op.f("ix_queue_job_queue_job_status"), "queue_job", ["status"], unique=False)
    op.create_table(
        "queue_worker",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("queues", sa.ARRAY(sa.String(length=128)), nullable=False),
        sa.Column("concurrency", sa.Integer(), nullable=False),
        sa.Column(
            "last_heartbeat",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_queue_worker")),
    )
    op.create_table(
        "tenant",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("settings", sa.JSON(), nullable=True),
        sa.Column("is_default", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["user.id"], name=op.f("fk_tenant_owner_id_user"), use_alter=True
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tenant")),
    )
    op.create_index(op.f("ix_tenant_tenant_active"), "tenant", ["active"], unique=False)
    op.create_index(op.f("ix_tenant_tenant_slug"), "tenant", ["slug"], unique=True)
    op.create_table(
        "queue_job_event",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("job_id", sa.BigInteger(), nullable=False),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["queue_job.id"],
            name=op.f("fk_queue_job_event_job_id_queue_job"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_queue_job_event")),
    )
    op.create_index(
        op.f("ix_queue_job_event_queue_job_event_job_id"),
        "queue_job_event",
        ["job_id"],
        unique=False,
    )
    op.create_table(
        "queue_worker_event",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("worker_id", sa.BigInteger(), nullable=False),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["worker_id"],
            ["queue_worker.id"],
            name=op.f("fk_queue_worker_event_worker_id_queue_worker"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_queue_worker_event")),
    )
    op.create_index(
        op.f("ix_queue_worker_event_queue_worker_event_worker_id"),
        "queue_worker_event",
        ["worker_id"],
        unique=False,
    )
    op.create_table(
        "role",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenant.id"], name=op.f("fk_role_tenant_id_tenant")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_role")),
        sa.UniqueConstraint("tenant_id", "name", name=op.f("uq_role_tenant_id_name")),
    )
    op.create_index(op.f("ix_role_role_active"), "role", ["active"], unique=False)
    op.create_index(op.f("ix_role_role_tenant_id"), "role", ["tenant_id"], unique=False)
    op.create_table(
        "user",
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("last_name", sa.String(length=100), nullable=False),
        sa.Column("avatar_url", sa.String(length=512), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenant.id"], name=op.f("fk_user_tenant_id_tenant")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user")),
    )
    op.create_index(op.f("ix_user_user_active"), "user", ["active"], unique=False)
    op.create_index(op.f("ix_user_user_email"), "user", ["email"], unique=True)
    op.create_index(op.f("ix_user_user_tenant_id"), "user", ["tenant_id"], unique=False)
    op.create_index(op.f("ix_user_user_username"), "user", ["username"], unique=True)
    op.create_table(
        "asset",
        sa.Column("key", sa.String(length=1024), nullable=False),
        sa.Column("content_type", sa.String(length=255), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("blurhash", sa.String(length=100), nullable=True),
        sa.Column("original_filename", sa.String(length=255), nullable=True),
        sa.Column("uploader_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenant.id"], name=op.f("fk_asset_tenant_id_tenant")
        ),
        sa.ForeignKeyConstraint(
            ["uploader_id"], ["user.id"], name=op.f("fk_asset_uploader_id_user")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_asset")),
    )
    op.create_index(op.f("ix_asset_asset_tenant_id"), "asset", ["tenant_id"], unique=False)
    op.create_index(op.f("ix_asset_asset_uploader_id"), "asset", ["uploader_id"], unique=False)
    op.create_table(
        "audit_log",
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column("action", sa.String(length=50), nullable=False),
        sa.Column("resource_type", sa.String(length=100), nullable=False),
        sa.Column("resource_id", sa.String(length=36), nullable=False),
        sa.Column("changes", sa.JSON(), nullable=True),
        sa.Column("ip", sa.String(length=45), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["actor_id"], ["user.id"], name=op.f("fk_audit_log_actor_id_user")),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenant.id"], name=op.f("fk_audit_log_tenant_id_tenant")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
    )
    op.create_index(op.f("ix_audit_log_audit_log_action"), "audit_log", ["action"], unique=False)
    op.create_index(
        op.f("ix_audit_log_audit_log_actor_id"), "audit_log", ["actor_id"], unique=False
    )
    op.create_index(
        op.f("ix_audit_log_audit_log_resource_id"), "audit_log", ["resource_id"], unique=False
    )
    op.create_index(
        op.f("ix_audit_log_audit_log_resource_type"), "audit_log", ["resource_type"], unique=False
    )
    op.create_index(
        op.f("ix_audit_log_audit_log_resource_type_audit_log_resource_id"),
        "audit_log",
        ["resource_type", "resource_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_audit_log_audit_log_tenant_id"), "audit_log", ["tenant_id"], unique=False
    )
    op.create_table(
        "identity",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("provider_subject_id", sa.String(length=255), nullable=False),
        sa.Column("credential_hash", sa.String(length=255), nullable=True),
        sa.Column("access_token_enc", sa.String(length=1024), nullable=True),
        sa.Column("refresh_token_enc", sa.String(length=1024), nullable=True),
        sa.Column("token_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("scopes", sa.String(length=512), nullable=True),
        sa.Column("provider_email", sa.String(length=255), nullable=True),
        sa.Column("provider_display_name", sa.String(length=255), nullable=True),
        sa.Column("provider_avatar_url", sa.String(length=512), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk_identity_user_id_user"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_identity")),
        sa.UniqueConstraint(
            "provider", "provider_subject_id", name=op.f("uq_identity_provider_provider_subject_id")
        ),
    )
    op.create_index(op.f("ix_identity_identity_provider"), "identity", ["provider"], unique=False)
    op.create_index(op.f("ix_identity_identity_user_id"), "identity", ["user_id"], unique=False)
    op.create_table(
        "notification",
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("audience", sa.String(length=20), nullable=False),
        sa.Column("urgency", sa.Integer(), nullable=False),
        sa.Column("target_id", sa.UUID(), nullable=True),
        sa.Column("sender_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["sender_id"], ["user.id"], name=op.f("fk_notification_sender_id_user")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenant.id"], name=op.f("fk_notification_tenant_id_tenant")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notification")),
    )
    op.create_index(
        op.f("ix_notification_notification_tenant_id"), "notification", ["tenant_id"], unique=False
    )
    op.create_table(
        "role_permission",
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.Column("permission_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["permission_id"],
            ["permission.id"],
            name=op.f("fk_role_permission_permission_id_permission"),
        ),
        sa.ForeignKeyConstraint(
            ["role_id"], ["role.id"], name=op.f("fk_role_permission_role_id_role")
        ),
        sa.PrimaryKeyConstraint("role_id", "permission_id", name=op.f("pk_role_permission")),
    )
    op.create_table(
        "session",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.String(length=255), nullable=False),
        sa.Column("ip", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.String(length=512), nullable=True),
        sa.Column("fingerprint", sa.String(length=255), nullable=True),
        sa.Column("country_code", sa.String(length=2), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], name=op.f("fk_session_user_id_user")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_session")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_session_token_hash")),
    )
    op.create_index(op.f("ix_session_session_user_id"), "session", ["user_id"], unique=False)
    op.create_table(
        "user_role",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["role_id"], ["role.id"], name=op.f("fk_user_role_role_id_role")),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], name=op.f("fk_user_role_user_id_user")),
        sa.PrimaryKeyConstraint("user_id", "role_id", name=op.f("pk_user_role")),
    )
    op.create_table(
        "notification_interaction",
        sa.Column("notification_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("dismissed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reaction", sa.String(length=20), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["notification_id"],
            ["notification.id"],
            name=op.f("fk_notification_interaction_notification_id_notification"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk_notification_interaction_user_id_user")
        ),
        sa.PrimaryKeyConstraint(
            "notification_id", "user_id", name=op.f("pk_notification_interaction")
        ),
    )
    op.create_index(
        op.f("ix_notification_interaction_notification_interaction_dismissed_at"),
        "notification_interaction",
        ["dismissed_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_notification_interaction_notification_interaction_dismissed_at"),
        table_name="notification_interaction",
    )
    op.drop_table("notification_interaction")
    op.drop_table("user_role")
    op.drop_index(op.f("ix_session_session_user_id"), table_name="session")
    op.drop_table("session")
    op.drop_table("role_permission")
    op.drop_index(op.f("ix_notification_notification_tenant_id"), table_name="notification")
    op.drop_table("notification")
    op.drop_index(op.f("ix_identity_identity_user_id"), table_name="identity")
    op.drop_index(op.f("ix_identity_identity_provider"), table_name="identity")
    op.drop_table("identity")
    op.drop_index(op.f("ix_audit_log_audit_log_tenant_id"), table_name="audit_log")
    op.drop_index(
        op.f("ix_audit_log_audit_log_resource_type_audit_log_resource_id"), table_name="audit_log"
    )
    op.drop_index(op.f("ix_audit_log_audit_log_resource_type"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_audit_log_resource_id"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_audit_log_actor_id"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_audit_log_action"), table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_index(op.f("ix_asset_asset_uploader_id"), table_name="asset")
    op.drop_index(op.f("ix_asset_asset_tenant_id"), table_name="asset")
    op.drop_table("asset")
    op.drop_index(op.f("ix_user_user_username"), table_name="user")
    op.drop_index(op.f("ix_user_user_tenant_id"), table_name="user")
    op.drop_index(op.f("ix_user_user_email"), table_name="user")
    op.drop_index(op.f("ix_user_user_active"), table_name="user")
    op.drop_table("user")
    op.drop_index(op.f("ix_role_role_tenant_id"), table_name="role")
    op.drop_index(op.f("ix_role_role_active"), table_name="role")
    op.drop_table("role")
    op.drop_index(
        op.f("ix_queue_worker_event_queue_worker_event_worker_id"), table_name="queue_worker_event"
    )
    op.drop_table("queue_worker_event")
    op.drop_index(op.f("ix_queue_job_event_queue_job_event_job_id"), table_name="queue_job_event")
    op.drop_table("queue_job_event")
    op.drop_index(op.f("ix_tenant_tenant_slug"), table_name="tenant")
    op.drop_index(op.f("ix_tenant_tenant_active"), table_name="tenant")
    op.drop_table("tenant")
    op.drop_table("queue_worker")
    op.drop_index(op.f("ix_queue_job_queue_job_status"), table_name="queue_job")
    op.drop_index(
        op.f("ix_queue_job_queue_job_queueing_lock"),
        table_name="queue_job",
        postgresql_where=sa.text("status = 'todo'"),
    )
    op.drop_index(op.f("ix_queue_job_queue_job_queue_name"), table_name="queue_job")
    op.drop_index(
        op.f("ix_queue_job_queue_job_priority_queue_job_id"),
        table_name="queue_job",
        postgresql_where=sa.text("status = 'todo'"),
    )
    op.drop_index(
        op.f("ix_queue_job_queue_job_execution_lock"),
        table_name="queue_job",
        postgresql_where=sa.text("status = 'doing'"),
    )
    op.drop_table("queue_job")
    op.drop_index(op.f("ix_permission_permission_codename"), table_name="permission")
    op.drop_table("permission")
    # ### end Alembic commands ###
